[build]
  command = "npm start"
  publish = "frontend/dist"
    cache = [
    "node_modules"
  ]

[context.production.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://clinty2710:Studman081!@thefaves.2hunxaq.mongodb.net"
  # other environment variables
