[build]
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.development.environment]
  NODE_ENV = "development"
  SESSION_SECRET = "your-session-secret"
  REACT_APP_API_BASE_URL = "https://thefaves-8616b810d2fc.herokuapp.com"
  MONGODB_URI = "your-mongodb-uri"
  REACT_APP_GOOGLE_BOOKS_API_KEY = "your-google-books-api-key"
  RAPIDAPI_KEY = "your-rapidapi-key"
  THEMOVIEDB_API_TOKEN = "your-tmdb-api-token"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://myfavessite.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
