[build]
  command = "npm run build"
  publish = "frontend/dist"

[context.production.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://clinty2710:Studman081!@thefaves.2hunxaq.mongodb.net"
  # other environment variables

[[plugins]]
  package = "@netlify/plugin-functions-install-node-modules"

[build.environment]
  NODE_VERSION = "14" # or any other version compatible with your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
