[build]
  command = "npm start"
  publish = "frontend/dist"

[context.production.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://clinty2710:Studman081!@thefaves.2hunxaq.mongodb.net"

[context.production]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
