[build]
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[context.production.environment]
  NODE_ENV = "development"
  MONGODB_URI = "mongodb+srv://clinty2710:Studman081!@thefaves.2hunxaq.mongodb.net/?retryWrites=true&w=majority&appName=TheFaves"
