[build]
  command = "npm run build"
  publish = "frontend/dist"

[context.production.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://clinty2710:Studman081!@thefaves.2hunxaq.mongodb.net"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
